spring.application.name=Authentication

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=admin
spring.datasource.password=uO9gknMg89
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=6000

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

eureka.instance.metadata-map.gateway-enabled=true